version: '3'

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    volumes:
      - ./zookeeper-persistence:/bitnami/zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      #- ZOO_ENABLE_AUTH=yes
      #- ZOO_SERVER_USERS=kafka
      #- ZOO_SERVER_PASSWORDS=kafka_password

  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
      - '29092:29092'
    volumes:
      - ./kafka-persistence:/bitnami/kafka
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=LISTENER_BOB://kafka:9092,LISTENER_FRED://0.0.0.0:29092
      - KAFKA_ADVERTISED_LISTENERS=LISTENER_BOB://kafka:9092,LISTENER_FRED://localhost:29092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=LISTENER_BOB:PLAINTEXT,LISTENER_FRED:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=LISTENER_BOB
      # SASL authentication over SSL
      #- KAFKA_CFG_LISTENERS=SASL_SSL://:9092
      #- KAFKA_CFG_ADVERTISED_LISTENERS=SASL_SSL://:9092
      #- KAFKA_ZOOKEEPER_USER=kafka
      #- KAFKA_ZOOKEEPER_PASSWORD=kafka_password
    depends_on:
      - zookeeper

  # kafka-explore:
  #   image: 'danielqsj/kafka-exporter'
  #   ports:
  #     - '9308:9308'
  #   command: ["--kafka.server=kafka:9092"]
  #   depends_on:
  #     - kafka

  kafka-manager:
    image: 'sheepkiller/kafka-manager'
    ports:
      - '9091:9000'
    environment:
      - ZK_HOSTS=zookeeper:2181
      - APPLICATION_SECRET=letmein
    depends_on:
      - kafka

  kafkacat:
    image: confluentinc/cp-kafkacat
    command: sleep infinity
    
