version: '3'

services:
  redis:
    image: redis:6
    ports:
      - 6379:6379
    volumes:
      - ./data0:/data 
      - ./etc/redis.conf:/usr/local/etc/redis/redis.conf
    commands:
      ["redis-server", "/usr/local/etc/redis/redis.conf"]
    
